"""Xfail the AppleGPU known-failure baseline without patching the upstream suite.

CI copies this next to Triton's test tree as conftest.py. The baseline lives in
applegpu_xfails.txt (`<nodeid> <reason>`), generated by gen_applegpu_xfails.py
from the per-reason buckets in applegpu-xfails/.

Marks are non-strict: a test that starts passing reports XPASS rather than
failing the run, so fixes surface without breaking CI.
"""

import pathlib

import pytest

_BASELINE = pathlib.Path(__file__).parent / "applegpu_xfails.txt"


def _load():
    known = {}
    if not _BASELINE.is_file():
        return known
    for line in _BASELINE.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        nodeid, _, reason = line.rpartition(" ")
        if nodeid:
            known[nodeid] = reason
    return known


_KNOWN = _load()


def _key(nodeid):
    # pytest reports nodeids relative to its rootdir, which differs between a
    # collect-only pass and a run; only the file-and-test tail is stable. Test
    # params can contain '/', so split off the directories before the '::'.
    file_part, sep, rest = nodeid.partition("::")
    return f"{file_part.split('/')[-1]}{sep}{rest}"


def pytest_collection_modifyitems(config, items):
    if not _KNOWN:
        return
    marked = 0
    for item in items:
        reason = _KNOWN.get(_key(item.nodeid))
        if reason:
            item.add_marker(pytest.mark.xfail(reason=reason, strict=False))
            marked += 1
    print(f"\nAppleGPU baseline: xfailed {marked} of {len(items)} collected")
