#!/usr/bin/env python3
"""Flatten the per-reason baseline buckets into the single file CI consumes.

Reads ci/applegpu-xfails/<reason>.txt (raw `FAILED <nodeid> - <msg>` pytest
lines, one file per failure category) and writes ci/applegpu_xfails.txt as
`<nodeid> <reason>` rows, so the conftest does no parsing at collection time.
"""

import pathlib
import sys

HERE = pathlib.Path(__file__).parent
SRC = HERE / "applegpu-xfails"
OUT = HERE / "applegpu_xfails.txt"


def main():
    rows = {}
    for path in sorted(SRC.glob("*.txt")):
        reason = path.stem
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line.startswith("FAILED "):
                continue
            nodeid = line[len("FAILED "):].split(" - ", 1)[0].strip()
            if "::" not in nodeid:
                continue
            # Key on the file-and-test tail: pytest's nodeid is rootdir-relative
            # and the rootdir differs between collection and run. Only the
            # directories are stripped; test params can contain '/'.
            file_part, rest = nodeid.split("::", 1)
            rows.setdefault(f"{file_part.split('/')[-1]}::{rest}", reason)

    with OUT.open("w") as f:
        f.write("# AppleGPU known-failure baseline: <nodeid> <reason>\n")
        f.write(f"# Generated by {pathlib.Path(__file__).name}; do not hand-edit.\n")
        for nodeid in sorted(rows):
            f.write(f"{nodeid} {rows[nodeid]}\n")

    print(f"wrote {OUT} ({len(rows)} nodeids)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
